sbatch submission failures do not continue

diff --git a/profiles/slurm/submit b/profiles/slurm/submit
--- a/profiles/slurm/submit
+++ b/profiles/slurm/submit
@@ -50,6 +50,18 @@ fi
 export DEP_STRING
 export SBATCH_ARGS
 
-# need to return just the job ID part to enable snakemake to build dependencies correctly
-# $@ should still contain the job execution script generated by snakemake
-sbatch ${DEP_STRING} ${SBATCH_ARGS} $@ | cut -f4 -d' '
+# Submit the job, retrying if sbatch fails to submit the job.
+# It is important to not continue after a failure otherwise the JOBID is reported as an empty string.
+JOBID=''
+while true
+do
+    # need to return just the job ID part to enable snakemake to build dependencies correctly
+    # $@ should still contain the job execution script generated by snakemake
+    JOBID=$(sbatch ${DEP_STRING} ${SBATCH_ARGS} $@ | cut -f4 -d' ')
+    if [ "$JOBID" != '' ]; then
+        break
+    fi
+    echo "Failed to submit job to slurm, waiting 10 seconds" 1>&2
+    sleep 10
+done
+echo -n $JOBID
